# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_active',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='customer_tel',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_addres',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='nmb',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
