# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-03 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181103_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_product',
            field=models.BooleanField(default=True),
        ),
    ]
