# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_new_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_product',
            field=models.BooleanField(default=False),
        ),
    ]
