# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-11-03 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_top_baner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='top_baner',
            new_name='top',
        ),
    ]
