# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-04 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productsubcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='name_category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productsubcategory',
            old_name='name_subcategory',
            new_name='name',
        ),
    ]
