# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-04 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20181204_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='name_category',
        ),
        migrations.RenameField(
            model_name='productsubcategory',
            old_name='name',
            new_name='name_subcategory',
        ),
    ]
