# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-05 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20181205_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_category',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
