# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-08 17:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categ',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.Categ', verbose_name='Родитель'),
        ),
    ]
