# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-08 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20181208_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categ',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductSubCategory',
        ),
    ]
