# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-12-08 21:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20181209_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categ',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='products.Category'),
        ),
    ]
