# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-01 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=products.models.image_folder),
        ),
    ]
